### ISSUE TITLE
coolstore-bw build constantly fails (Maven build error)

### ISSUE THREAD

**Issue by karstengresch** [jbossdemocentral/coolstore-microservice#45]
Hi all,

trying to get a running coolstore-gw image running, it fails during the Maven build process:

```
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.fabric8:fabric8-project-bom-camel-spring-boot:pom:2.2.170.redhat-000010 in jboss.fuse (https://repo.fusesource.com/nexus/content/groups/public/)
at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
... 27 more
[ERROR]     'dependencies.dependency.version' for org.apache.camel:camel-spring-boot-starter:jar is missing. @ line 37, column 20
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-web:jar is missing. @ line 41, column 17
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-actuator:jar is missing. @ line 45, column 17
[ERROR]     'dependencies.dependency.version' for org.apache.camel:camel-servlet-starter:jar is missing. @ line 49, column 17
[ERROR]     'dependencies.dependency.version' for org.apache.camel:camel-hystrix-starter:jar is missing. @ line 53, column 20
[ERROR]     'dependencies.dependency.version' for org.apache.camel:camel-http4-starter:jar is missing. @ line 58, column 15
[ERROR]     'dependencies.dependency.version' for org.apache.camel:camel-jsonpath-starter:jar is missing. @ line 62, column 15
[ERROR]     'dependencies.dependency.version' for org.apache.camel:camel-jackson-starter:jar is missing. @ line 66, column 15
[ERROR]     'dependencies.dependency.version' for org.apache.camel:camel-swagger-java-starter:jar is missing. @ line 70, column 16
[ERROR]     'dependencies.dependency.version' for junit:junit:jar is missing. @ line 78, column 15
[ERROR]     'dependencies.dependency.version' for org.springframework:spring-test:jar is missing. @ line 83, column 15
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar is missing. @ line 88, column 15
[ERROR]     'dependencies.dependency.version' for org.jboss.arquillian.junit:arquillian-junit-container:jar is missing. @ line 93, column 15
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
Aborting due to error code 1 for Maven build    
error: build error: non-zero (13) exit code from registry.access.redhat.com/jboss-fuse-6/fis-java-openshift@sha256:efec2da0909b700711f819791d10dfcb6c7a33fdbf454c870cebdbacb18c1ff4
```

(Full details: [2017-03-24_coolstore-gw-build.txt](https://github.com/jbossdemocentral/coolstore-microservice/files/868514/2017-03-24_coolstore-gw-build.txt)).

Any chance getting the demo running on my machine (32 GByte, 8core, SSDs) running?

Set up as per instructions, build fails after

``
oc process -f openshift/coolstore-template.yaml | oc create -f -
``

_not_ the provision-demo script.

Thanks!

Best wishes,

Karsten

**Comment by siamaksade** [comment]
You need to pass a url to a maven repo that contains Red Hat enterprise artifacts. You can do that by setting the MAVEN_MIRROR_URL parameters on the template. The provisioning script automatically does that.

`io.fabric8:fabric8-project-bom-camel-spring-boot:pom:2.2.170.redhat-000010` is an enteprrise Red Hat jar file that doesn't exist in central maven repository.

This demo runs on your laptop :)

**Comment by karstengresch** [comment]
Hi Siamak,

thanks for your reply. I'd like to change the documentation then as it gave me the impression, I just had to run _oc process_ as given above and then I'd be all set.

I wonder to which MAVEN_MIRROR_URL the parameters should be set to, though. 

As per my understanding, the provision script creates a nexus pod (which b.t.w. never comes up on my local installation, but that'll be addressed in a separate issue) and the service URL of it is then used as the MAVEN_MIRRO_URL.

So the documentation should describe you need to set up your own Nexus/Artifactory, then change coolstore-template.yml to the Maven repo service URL, then run _oc process_ w/ it. Correct?
